name: Hello World
on: [push]

jobs:
  run-shell-command:
    runs-on: ubuntu-18.04
    steps:
      - name: hello world
        run: echo hello-world
      - name: check node version
        run: 
          node -v 
          npm -v
      - name: python command
        run: 
          import platform
          print(platform.processor())
        shell: python